name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4

      - name: Setup environment
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac #v2
        with:
          experimental: true
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Lint
        run: |
          go vet ./...
          golangci-lint run ./...

      - name: Test
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 #v4
        with:
          files: coverage.out
          fail_ci_if_error: false
        continue-on-error: true
