name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases-created: ${{ steps.release.outputs.releases_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 #v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go

      - name: Release-Please Debug
        run: |
          echo "${{ steps.release.outputs }}" | jq -r

  dispatch-publish:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch publish (stable)
        if: needs.release-please.outputs.releases-created == 'true'
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 #v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: publish-package
          client-payload: |
            {
              "tag": "${{ needs.release-please.outputs.tag-name }}"
            }

      - name: Dispatch publish (prerelease)
        if: needs.release-please.outputs.releases-created != 'true'
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 #v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: publish-package
          client-payload: |
            {
              "prerelease": true
            }
